### ISSUE TITLE
Duplicate Key issue

### ISSUE THREAD

**Issue by elenirotsides** [Peer-Stevens/peer#207]
There is a possibility of there being duplicate keys apparently and we should account for this. Found this bug while testing https://github.com/Peer-Stevens/peer/pull/197 , but is not a result of that PR.

![IMG_0342](https://user-images.githubusercontent.com/43190242/146251301-58be33d0-362b-42ba-be3b-58eb1671fcbb.PNG)

**Comment by carpenterd777** [comment]
Could you reproduce this error when you nothing else to work on?

**Comment by elenirotsides** [comment]
So sorry - I just saw your comment on this! @carpenterd777 I just tested and don't see the issue; the list of banks have changed since the last time I tested and therefore cannot reproduce this. I'll close this for now and we can reopen it if the issue arises at any point in the future.

**Comment by elenirotsides** [comment]
Wait I lied, it wasn't banks, it was ATMs

**Comment by elenirotsides** [comment]
The issue still exists

**Comment by jlora23** [comment]
I had this issue previously in #58

**Comment by jlora23** [comment]
I can reproduce it as well if you guys need since it happens when I am home
