### ISSUE TITLE
Remove all eslint-ignores

### ISSUE THREAD

**Issue by carpenterd777** [Peer-Stevens/peer#63]
Let's nip this technical debt in the bud while its early. So far, we have been using `//eslint-disable-next-line @typescript-eslint/ban-types` for style props, typically because they are in the shape `StyleProp<object>` and `object` is not allowed in the aforementioned rule. There is some type that will fit better here than `object`, and we'll have to figure out what it is. It may be some union of types.

Resources:
[Image Style Props](https://reactnative.dev/docs/image-style-props)
[Text Style Props](https://reactnative.dev/docs/text-style-props)
[View Style Props](https://reactnative.dev/docs/view-style-props)
[Stylesheet](https://reactnative.dev/docs/stylesheet)

**Comment by georgettica** [comment]
Can I take a sliver of this?

**Comment by carpenterd777** [comment]
@georgettica Sure, go for it! Submit a PR whenever you'd like.
